fix(pkg): Upgrade grunt-contrib-imagemin
grunt-contrib-imagemin to ^1.0.0 because the ^0.9.2 versions throw the following error when building the app:

Warning: Running "imagemin:dist" (imagemin) task
Fatal error: Cannot read property 'contents' of undefinedbuilding: